/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiYoutubeOauthStartRouteImport } from './routes/api/youtube/oauth/start'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYoutubeOauthStartRoute = ApiYoutubeOauthStartRouteImport.update({
  id: '/api/youtube/oauth/start',
  path: '/api/youtube/oauth/start',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/api/youtube/oauth/start': typeof ApiYoutubeOauthStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/api/youtube/oauth/start': typeof ApiYoutubeOauthStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/api/youtube/oauth/start': typeof ApiYoutubeOauthStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/feed'
    | '/onboarding'
    | '/settings'
    | '/api/youtube/oauth/start'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/feed' | '/onboarding' | '/settings' | '/api/youtube/oauth/start'
  id:
    | '__root__'
    | '/'
    | '/feed'
    | '/onboarding'
    | '/settings'
    | '/api/youtube/oauth/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeedRoute: typeof FeedRoute
  OnboardingRoute: typeof OnboardingRoute
  SettingsRoute: typeof SettingsRoute
  ApiYoutubeOauthStartRoute: typeof ApiYoutubeOauthStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/youtube/oauth/start': {
      id: '/api/youtube/oauth/start'
      path: '/api/youtube/oauth/start'
      fullPath: '/api/youtube/oauth/start'
      preLoaderRoute: typeof ApiYoutubeOauthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeedRoute: FeedRoute,
  OnboardingRoute: OnboardingRoute,
  SettingsRoute: SettingsRoute,
  ApiYoutubeOauthStartRoute: ApiYoutubeOauthStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
